# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42d475eb4d41643f2c5aca2efe56da69c2971e9d3e06d103ec79db675aab8d7f52d221ef518d2fb88e50a6b8a4a66a467a7a46fd4e3b24fca132654e41400941

test:
  secret_key_base: a96bf6205ccf19f4216d5347de7ed2e96311e14046be62872568067725e0e2b2ccba8885821a53c46fc16f646c6c67b62da1be46b8581c73e84cec1c7c97f66f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
